name: Manual Workflow with Input

on:
  workflow_dispatch:
    inputs:
      environment:
        description: '选择部署环境'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      version:
        description: '发布版本号'
        required: true
        default: '1.0.0'
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 输出参数
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
